apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.queryFrontendFullname" . }}
  labels:
    {{- include "cortex.queryFrontendLabels" . | nindent 4 }}
    {{- with .Values.query_frontend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.query_frontend.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: 9095
      protocol: TCP
      name: grpclb
      targetPort: grpc
  selector:
    {{- include "cortex.queryFrontendSelectorLabels" . | nindent 4 }}
