apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.alertmanagerFullname" . }}
  labels:
    {{- include "cortex.alertmanagerLabels" . | nindent 4 }}
    {{- with .Values.alertmanager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.alertmanager.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.alertmanagerSelectorLabels" . | nindent 4 }}
