apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.fullname" . }}-memberlist
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7946
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
