apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.distributorFullname" . }}
  labels:
    {{- include "cortex.distributorLabels" . | nindent 4 }}
    {{- with .Values.distributor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.distributor.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.distributorSelectorLabels" . | nindent 4 }}
