{{- if ne (include "cortex.config" .) "blocks" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.tableManagerFullname" . }}
  labels:
    {{- include "cortex.tableManagerLabels" . | nindent 4 }}
    {{- with .Values.table_manager.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.table_manager.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.tableManagerSelectorLabels" . | nindent 4 }}
{{- end -}}
